### ISSUE TITLE
Gateway contracts feedbacks 

### ISSUE THREAD

**Issue by sarvesh-ost** [OpenST/mosaic-contracts#662]
1. Removed value token (Please double check the usage) 
https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/gateway/EIP20CoGateway.sol#L216

2. Rename `redeemProcess` -> redeem
https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/gateway/EIP20CoGateway.sol#L722

3. Remove the nonce parameter from EIP20 Gateway `stake` and EIP20CoGateway `redeem` method [Not 0.0.10 release]

4. Allow zero amount in `increaseSupply`. Also, Check UT if allows zero transfer. 
https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/gateway/EIP20CoGateway.sol#L1139

5. Try to make events specific to message bus states. The intention is to reduce the number of event types from the gateway.
 [Not 0.0.10 release]

6. Don't return penalty in case of progress with proof. Burn the penalty. Check progressStakeWithProof and progressRedeemWithProof

https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/gateway/EIP20CoGateway.sol#L569

https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/gateway/EIP20Gateway.sol#L500

7. Move deletion up 
https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/gateway/EIP20Gateway.sol#L1011

https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/gateway/EIP20CoGateway.sol#L451

8. Emit event on activating and deactivate Gateway 
https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/gateway/EIP20Gateway.sol#L1046

9. Move check that reward > stake/mint amount in confirmStakeIntent and confirmRedeemIntent 
https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/gateway/EIP20Gateway.sol#L1219
```
require(
            rewardAmount_ < redeemAmount_,
            "Reward amount must be less than redeem amount."
        );
```
 10. Make comment on general in gateway base. Stake and redeem terms shouldn't be used in gateway base. 
https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/gateway/GatewayBase.sol#L73

11. Change bounty unlock time to 7 days as per aux block time. 

https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/gateway/GatewayBase.sol#L79

12. Add circular buffer for storage roots. 
https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/gateway/GatewayBase.sol#L121

13. Improve variable names  in feeAmount method.
https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/gateway/GatewayBase.sol#L461

14 . Gateway nonce should start with `0`.
 https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/gateway/GatewayBase.sol#L686

15. In OST prime use  coin for base token(eth) and OST for token. 
https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/gateway/OSTPrime.sol#L58

16. Use co-gateway address explicitly 

https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/gateway/OSTPrime.sol#L256

17. Use `valueToken` instead of `token` accross contracts(OSTPrime, UtilityToken, EIP20CoGateway, EIP20Gateway and SimpleStake)
 https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/gateway/UtilityToken.sol#L79  

18. Change EIP20Interface to `address` 
https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/gateway/UtilityToken.sol#L79

19. Correct comment `Inbox of source chain` -> `Target chain`

https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/lib/MessageBus.sol#L245

20.  Rename messageStatus to inboxMessageStatus 

https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/lib/MessageBus.sol#L256

21. Remove dead code 
https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/lib/MessageBus.sol#L643

22. Clean bytes lib. Only keep the necessary methods.

**Comment by schemar** [comment]
@gulshanvasnani is it correct that I am assigned to this ticket?

**Comment by gulshanvasnani** [comment]
@schemar , This ticket has been self-assigned by you.
Then I assigned it to myself because i was doing `Change bounty unlock time to 7 days as per aux block time.` task.

**Comment by benjaminbollen** [comment]
keeping this ticket around for later review but all contract changes have been closed, barring severe security issues that would rise

**Comment by benjaminbollen** [comment]
New task for this issue: review which changes have not been made, and create a new ticket listing only those, please.

**Comment by schemar** [comment]
Converting to an epic to add sub-tasks.

**Comment by schemar** [comment]
1. Removed value token
    * #692
2. Rename `redeemProcess` -> redeem
    * #693
3. Remove the nonce parameter from EIP20 Gateway `stake` and EIP20CoGateway `redeem` method [Not `0.10` release]
    * #694
4. Allow zero amount in `increaseSupply`. Also, Check UT if allows zero transfer.
    * #695
5. Try to make events specific to message bus states. The intention is to reduce the number of event types from the gateway. [Not `0.10` release]
    * #696
6. ~Don't return penalty in case of progress with proof. Burn the penalty. Check progressStakeWithProof and progressRedeemWithProof (#668)~
7. ~Move deletion up (#663)~
8. Emit event on activating and deactivate Gateway 
    * #697
9. ~Move check that reward > stake/mint amount in confirmStakeIntent and confirmRedeemIntent (#666 😈)~
10. ~Make comment on general in gateway base. Stake and redeem terms shouldn't be used in gateway base (#690)~
11. ~Change bounty unlock time to 7 days as per aux block time. (#671)~
12. Add circular buffer for storage roots.
    * #698
13. Improve variable names  in feeAmount method.
    * #699
14. Gateway nonce should start with `0`.
    * #700
15. ~In OST prime use  coin for base token(eth) and OST for token. #686~
16. ~Use co-gateway address explicitly #674~
17. Use `valueToken` instead of `token` accross contracts(OSTPrime, UtilityToken, EIP20CoGateway, EIP20Gateway and SimpleStake)
    * #701
18. Change EIP20Interface to `address`
    * #702
19. ~Correct comment `Inbox of source chain` -> `Target chain` #688~
20. Rename messageStatus to inboxMessageStatus
    * #703
21. ~Remove dead code #664
22. ~Clean bytes lib. Only keep the necessary methods. #664 and #675~

**Comment by schemar** [comment]
Created new tickets for the remaining tasks. This is now considered an Epic. @benjaminbollen please check the new tickets.

**Comment by deepesh-kn** [comment]
All tickets in the epic are closed. Closing this epic.
