### ISSUE TITLE
Gateways should store roots in ring buffer

### ISSUE THREAD

**Issue by schemar** [OpenST/mosaic-contracts#698]
To have a constant size `O(1)` instead of a linear size `O(n)` depending on messages that will be sent with the gateways, the storage roots in gateway base should be stored in a circular buffer that prunes old storage roots.

In GatewayBase the messagebox offset should be made public, such that the proof generation can query the offset.

Was potentially done in #669

Regenerate the proof using the tool from #711

**Comment by sarvesh-ost** [comment]
`CircularBufferUint.sol` has an implementation of the circular buffer. 
If the `GatewayBase` extends `CircularBufferUint.sol` then _the position of message box_ in the EVM storage will change because of the variables declared in the `CircularBufferUint.sol`

_The position of message box_ i.e. `MESSAGE_OUTBOX_OFFSET` in the outbox is used to generate Merkel proofs. 
 This change looks like an interface change to me. Maybe there is a work around of this, which I am not aware of.

**Comment by benjaminbollen** [comment]
I suggest we use the inherited contract approach.  It is clearer to understand the storage layout, even if it changes the position.
